name: run tests

on:
  push:
    branches:
      - "main"
  pull_request:


jobs:
  pre-commit:
    name: pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies for pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

  test:
    name: "test"
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python: ["3.11", "3.12", "3.13"]
    defaults:
      run:
        shell: "bash -eo pipefail {0}"

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v3"
        with:
          python-version: "${{ matrix.python }}"
      - uses: "actions/cache@v3"
        id: "cache"
        with:
          path: "${{ env.pythonLocation }}"
          key: "test-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml', 'requirements/*') }}"
      - run: "python --version"
      - run: "python -mpip install -U pip"
      - run: "python -mpip --version"
      - run: "python -mpip install -r requirements/requirements.txt"
      - run: "python -mpip install -e ./"
      - name: "Run tests"
        run: "pytest -v"
